### ISSUE TITLE
Submit to PyPi

### ISSUE THREAD

**Issue by fjcaetano** [damianmoore/django-dynamic-dns#1]
First of all, thanks for the project. It seems great and I'm figuring my way around it.

I'm thinking of starting a Heroku app with this project and when I tried to install the package via pip I got the following log:

``` bash
(ddns)➜  ddns git:(master) ✗ pip install django-dynamic-dns
Downloading/unpacking django-dynamic-dns
  Could not find any downloads that satisfy the requirement django-dynamic-dns
Cleaning up...
No distributions at all found for django-dynamic-dns
```

I saw that the there's already a [django-dynamic-dns](https://pypi.python.org/pypi/django-dynamic-dns) package in pypi, but it can't be installed. I suppose the source code isn't configured.

**Comment by damianmoore** [comment]
Hi Flávio, thanks for your interest and for letting me know. I only added it to PyPI less than 2 weeks ago and it seemed to work for me then but now I get your error. I'll try and fix it soon on PyPI. In the mean time you can install it with this command:

``` bash
pip install https://github.com/damianmoore/django-dynamic-dns/tarball/0.1.2
```

**Comment by fjcaetano** [comment]
Thanks, I solved it by copying the `dynamicdns` app source into my project.

Abraços,
Flávio J V Caetano
